name: UsefulTricks
author: Articuling
version: 1.6
main: me.articuling.usefultricks.UsefulTricks
api-version: '1.20'
commands:
  pickup:
    description: Set to true/false if you can pickup items!
    aliases: [item]
  usefultricks:
      description: Allows to reload the plugin

permissions:
  usefultricks.command.pickup:
    description: Allows someone to turn on or off item pickup using /pickup
  usefultricks.command.reload:
    description: Allows someone to use the command /usefultricks reload